[package]
name = "nightcrawler"
version = "0.1.0"
authors = ["Jake Howard <git@theorangeone.net>"]

[dependencies]
clap = "2.30.0"
glib = "0.4.1"
gdk = "0.7.0"
gtk = { version = "0.3.0", features = ["v3_22"] }
relm = "0.11.0"
relm-derive = "0.11.0"
url = "1.7.0"
webkit2gtk = "0.3.0"
