version: 2.0

jobs:
    build:
        docker:
            - image: rust:1.24.0
        steps:
            - checkout
            - run: rustup component add rustfmt-preview
            - run: cargo fmt -- --write-mode=diff
            - run: cargo search  # Update registry outside build process
            - run: apt-get update && apt-get install libsoup2.4-dev libgtk-3-dev libwebkit2gtk-4.0-dev -y
            - run: cargo build
            - run: cargo build --release
